[package]
name = "tree-sitter-crasher"
version = "0.2.0"
edition = "2021"

[dependencies]
tree-sitter = "0.20.10"
tree-sitter-scala = { git = "https://github.com/tree-sitter/tree-sitter-scala", rev = "32b400e380cdbcad9c44ae2690ace081b790c18e" }
